### ISSUE TITLE
Updating multiple clients at the same time

### ISSUE THREAD

**Issue by gtaylor44** [dsuryd/dotNetify#92] opened 2018-05-19 03:11 UTC
Looks like a great library. I haven't seen anywhere in the documentation where you can update a group (of more than one users in one PushUpdate). Is this a feature that is on the roadmap?

**Comment by MrFoxPro** [comment] 2018-05-19 05:43
Duplicate of #58?

**Closed** 2018-06-02 01:11 UTC
Labels: duplicate
