### ISSUE TITLE
React componentWillUnmount not called on reload -> VM not destroyed

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#71] opened 2018-01-30 09:59 UTC
When the page is reloaded, the `componentWillUnmount` function is not called. The result is that I will have multiple instances of the c# Viewmodels running which won't get destroyed.
How can I reliably destroy the Viewmodel on page reload without making use of `VMControllerCacheExpiration`?

**Comment by dsuryd** [comment] 2018-01-30 16:06
It shouldn't be possible to have orphan C# view models on page reload, because the SignalR will raise  the disconnected event which then cause the VMController to destroy the view models.  You can test this by implementing IDisposable.  Put a breakpoint on the Dispose method, you'll see it will be hit when you reload the page.

**Comment by DG4ever** [comment] 2018-01-30 16:26
Thats exactly what I did. I even tested it with the react Template. I added the Dispose override to the Form.cs of the react template. When I switch between the Dashboard/Form/Table pages the Dispose method is called. But when pressing reload, the Dispose won’t get called and the viemodel stays alive. 
I noticed it in my project as my database connections were not disposed.

**Comment by dsuryd** [comment] 2018-01-31 16:24
I am able to reproduce the issue only when the transport is HTTP long polling.  Web socket works fine.   Can you confirm this is your case?  It appears the root cause is due to the SignalR alpha not sending disconnected event for long polling: [https://github.com/aspnet/SignalR/issues/1290](https://github.com/aspnet/SignalR/issues/1290).

**Comment by DG4ever** [comment] 2018-02-01 07:56
Yes thats correct, as I have windows 7 I don't have the option to use websockets. 
I will use my workaround until signalr fixes the issue.
Thanks for your help.

**Comment by dsuryd** [comment] 2018-06-14 16:36
Looks like SignalR team decided it's not a bug to fix on their end and leave it up to the developers to handle it the best way according to their own use case.  So I'll close this too.

To summarize the mentioned workaround:
Listen to the window's `beforeUnload` event and call `vm.$destroy()` when it's raised.

**Closed by dsuryd** 2018-06-14 16:36 UTC
Labels: signalR bug
