### ISSUE TITLE
MulticastVM:: _serviceScope ObjectDisposedException from VMController.Dispose() 

### ISSUE THREAD

**Issue by treg** [dsuryd/dotNetify#263] opened 2020-10-28 08:42 UTC
Using a MulticastVM, when VMController.Dispose() is called,
the  _serviceScope?.Dispose(); breaks the _serviceScope for the other MulticastVM instances.

VMController.cs line 200

Any suggestions?

**Comment by dsuryd** [comment] 2020-10-28 16:27
Steps to reproduce?  Preferably with one of the demo examples.

**Comment by treg** [comment] 2020-10-28 18:21
here you go...  the DisposableClass simulates EntityFrameworkCore.SqlServer
[Issue-263.zip](https://github.com/dsuryd/dotNetify/files/5454058/Issue-263.zip)

**Comment by dsuryd** [comment] 2020-11-06 04:18
I saw you put the `Debug.Assert` but it did not get triggered by the above steps.  Furthermore, each browser connection has its own `VMController` instance, so a browser refresh will only dispose its own instance.  I don't see how it can affect the `serviceScope` of the other browser's `VMController` instance?

**Comment by treg** [comment] 2020-11-06 11:41
Ok, let me rework the example

**Comment by sks-ttaylor** [comment] 2020-11-16 12:05
Here you go...

https://github.com/sks-ttaylor/Dotnetify_263

**Comment by dsuryd** [comment] 2020-11-22 23:04
Thank you for the repo, I think I finally understand the issue.  You are injecting a service instance to the multicast VM, but since the service instance is scoped to the first connection that instantiates the VM, when that connection goes away through browser closing/refreshing, the service instance is disposed along with the connection.  Since the multicast VM instance is kept until all associated connections are gone, the instance is left holding a reference to the disposed object.

This is more of a 'gotcha' than a bug.  Given that their lifetimes are tied to a specific connection, both scoped and transient will not be appropriate for injection to multicast VMs.  My suggestion is to use the singleton lifetime, or if you want to provide your own scoped service provider, override the default VM instantiation with your own through the `IDotNetifyConfiguration::SetFactoryMethod()`.

**Comment by sks-ttaylor** [comment] 2020-11-23 01:53
Thank for your response.

You stated it concisely.

Let me research further.

Treg



On Nov 22, 2020 5:04 PM, Dicky Suryadi <notifications@github.com> wrote:

Thank you for the repo, I think I finally understand the issue. You are injecting a service instance to the multicast VM, but since the service instance is scoped to the first connection that instantiates the VM, when that connection goes away through browser closing/refreshing, the service instance is disposed along with the connection. Since the multicast VM instance is kept until all associated connections are gone, the instance is left holding a reference to the disposed object.

This is more of a 'gotcha' than a bug. Given that their lifetimes are tied to a specific connection, both scoped and transient will not be appropriate for injection to multicast VMs. My suggestion is to use the singleton lifetime, or if you want to provide your own scoped service provider, override the default VM instantiation with your own through the IDotNetifyConfiguration::SetFactoryMethod().

**Closed** 2020-11-23 01:55 UTC
